name = "trwa/cardamove"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'trwa/cardamove'"

[repository]
user = "trwa"
project = "cardamove"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"